### ISSUE TITLE
Changing Starters in GTI Reboots to Top Menu

### ISSUE THREAD

**Issue by XModxGodX** [evandixon/SkyEditor.ROMEditor#103]
For whatever reason the editor won't let me change Pikachu as a starter or any of the starters movesets, if I leave portrait or Model patching checked the entire game crashes on boot-up. And even when I didn't patch them every time I highlight the edited starter I want to pick it reboots to the menu with the graphics from the starter select still on screen.

**Comment by evandixon** [comment]
> the editor won't let me change Pikachu as a starter
That's a known issue. For whatever reason, the game is hard-coded to ensure both Pikachu and Tepig are available as starters, and fixing that isn't high priority since the other 3 are editable.

> or any of the starters movesets
Unlike Pokémon Super Mystery Dungeon, in Gates to Infinity, the starter moves are determined using the level-up data.

> if I leave portrait or Model patching checked the entire game crashes on boot-up. And even when I didn't patch them every time I highlight the edited starter I want to pick it reboots to the menu with the graphics from the starter select still on screen.
Which starter(s) did you pick?

**Comment by XModxGodX** [comment]
I tried Jolteon over Snivy. Another occurrence just for the sake of testing was Vaporeon over Oshawott same thing happened. I even tried the March 12th release which is supposedly when it was first implemented still no luck.

Also I found that the movesets seem to be about 8 bytes after starter ID in fixed_pokemon.bin (also pikachu has fakeout which is an egg move)

**Comment by evandixon** [comment]
OK, I think I got it working in the latest commit. [Please give it a try.](https://teamcity.projectpokemon.org/repository/download/SkyEditor_SkyEditorROMEditor_B/49185:id/SkyEditor.ROMEditor.UI.WPF%20Build%20214.zip)
![image](https://user-images.githubusercontent.com/2699524/57184842-62477000-6e87-11e9-99ad-2eb24e2959cb.png)

**Comment by XModxGodX** [comment]
Nope still not working. I don't think it matters but I'm using the files from: solution/ project/ raw files I noticed there was some sort of .mod file that appears in the output folder but I don't know what to do with it.

![2019-05-04_13-28-25 992_top](https://user-images.githubusercontent.com/22751086/57185024-5ce32900-6e79-11e9-9946-47cac105a943.jpg)

**Comment by evandixon** [comment]
When you tried again, did you create a new solution, or rebuild the existing project? Due to the nature of the bug I fixed, a new solution was created.

If you didn't create a new solution, this modpack has the starters Vaporeon, Jolteon, and Zorua if you want to avoid waiting and if these are to your liking: 
[ModPack 1.0.0.zip](https://github.com/evandixon/SkyEditor.ROMEditor/files/3144869/ModPack.1.0.0.zip).

If you _did_ create a new solution, and it still failed, then please send me the modpack zip so I can investigate further.  Also let me know when exactly it failed. Using the latest version I got all the way through the scene where the player falls out of the sky, but I quit before the landing.

**Comment by XModxGodX** [comment]
I created a new project but I used the same solution. I'll start over from scratch for the sake of testing but thanks for the files.
